name: Notify the lib repo about changes in the docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify the lib repo about changes
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.NOTIFY_LIB_REPO }} \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/itihon/isomorphic-validation/dispatches \
            -d '{"event_type":"docs-changed"}'
